export const AUTHORS_DATA = [
  {
    id: 1,
    name: "Elara Vance",
    username: "elaravance",
    bio: "Writes on minimalism, architecture, and the quiet geometry of everyday design.",
    category: "DESIGN",
    image: null,
    postCount: 12,
    followCount: 1840,
  },
  {
    id: 2,
    name: "Julian Roth",
    username: "julianroth",
    bio: "Essayist exploring aesthetics, ethics, and the philosophy of taste in modern life.",
    category: "ESSAYS",
    image: null,
    postCount: 8,
    followCount: 942,
  },
  {
    id: 3,
    name: "Mei Tanaka",
    username: "meitanaka",
    bio: "Covers frontend engineering, developer tools, and the craft of building for the web.",
    category: "TECHNOLOGY",
    image: null,
    postCount: 21,
    followCount: 3210,
  },
  {
    id: 4,
    name: "Amara Osei",
    username: "amaraosei",
    bio: "Cultural critic writing on hyper-connectivity, status, and the modern attention economy.",
    category: "CULTURE",
    image: null,
    postCount: 15,
    followCount: 2075,
  },
  {
    id: 5,
    name: "Theo Marchetti",
    username: "theomarchetti",
    bio: "Architect and writer documenting concrete brutalism and material honesty in design.",
    category: "ARCHITECTURE",
    image: null,
    postCount: 6,
    followCount: 588,
  },
  {
    id: 6,
    name: "Priya Nair",
    username: "priyanair",
    bio: "Backend engineer writing deep-dives on distributed systems and clean architecture.",
    category: "TECHNOLOGY",
    image: null,
    postCount: 18,
    followCount: 2740,
  },
];

// TODO (post-MVP): replace this static dummy data with a real API call,
// e.g. GET /api/user/suggestions or a dedicated /api/user/authors endpoint,
// once that backend route exists.