spring:
  application:
    name: ${SPRING_APPLICATION_NAME:bms}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS}
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS}

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8080

admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}
  name: ${ADMIN_NAME}

app:
  frontend:
    base-url: http://localhost:5173